json.id product.id
json.title product.title
json.chef product.chef
json.prep_time product.prep_time
json.image_url product.image_url
json.ingredients product.ingredients
json.directions product.directions
json.created_at product.created_at
json.updated_at product.updated_at